/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-04-30 12:10:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Nossaq Login Page</title>\r\n");
      out.write("</head>\r\n");
      out.write("\t<link rel='stylesheet' type='text/css' href='css/login.css' />\r\n");
      out.write("\t<script type='text/javascript' src='scripts/LoginRegister.js'></script>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<table class=\"table\"><tr><td>\r\n");
      out.write("\t\t<a href=login.jsp><img src=\"images/nossaq.png\" alt=\"HomePage\" class=\"center\"></a></td></tr></table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<table class=\"table\" style=\" margin-top: -14%;\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<form id=\"login_form\" name=\"login_form\" class=\"forms login-form\" action=\"LoginRegister\" method=\"post\">\r\n");
      out.write("\t\t    \t<div class=\"header\">\r\n");
      out.write("\t    \t\t\t<h1>Login Form</h1>\r\n");
      out.write("\t    \t\t\t<span>Fill out the form below to login Nossaq system</span>\r\n");
      out.write("\t    \t\t</div>\r\n");
      out.write("\t   \t    \t<div class=\"content\">\r\n");
      out.write("\t\t\t       <input id=\"userfield\" type=\"text\" class=\"input username\" name=\"username\" value=\"Username\" onfocus=\"this.value=''\"><label style=\"visibility: hidden\" id=\"username_alert\" class=\"alert\"> Username field cannot be empty</label>\r\n");
      out.write("\t\t\t       <input id=\"passfield\" type=\"password\" class=\"input password\" name=\"password\" value=\"Password\" onfocus=\"this.value=''\"><label style=\"visibility: hidden\" id=\"password_alert\" class=\"alert\"> Password field cannot be empty</label>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"footer\">\r\n");
      out.write("\t\t\t       <input id=\"login_submit\" type=\"submit\" class=\"button\" onclick=\"return isEmpty( this.id);\" name=\"submit\" value=\"Login\">\r\n");
      out.write("\t\t\t       <a class=\"forgot\" href=\"forgot.jsp\">Forgot Pass</a>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t </td>\r\n");
      out.write("\t <td> \r\n");
      out.write("\t\t<form id=\"register_form\" name=\"register_form\" class=\"forms register-form\" action=\"LoginRegister\" method=\"post\">\r\n");
      out.write("         \t<div class=\"header\">\r\n");
      out.write("    \t\t\t<h1>Register Information</h1>\r\n");
      out.write("    \t\t\t<span>Fill out the form below to sign up Nossaq system</span>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"content\">\r\n");
      out.write("\t\t         <input id=\"namefield\" type=\"text\" name=\"name\" class=\"input\" value=\"Name\" onfocus=\"this.value=''\"><br><label class=\"alert\" style=\"visibility: hidden\" id=\"name_alert\"> Name field cannot be empty</label>\r\n");
      out.write("\t\t         <input id=\"surnamefield\" type=\"text\" class=\"input\" name=\"surname\" value=\"Surname\" onfocus=\"this.value=''\"><label class=\"alert\" style=\"visibility: hidden\" id=\"surname_alert\"> Surname field cannot be empty</label>\r\n");
      out.write("\t\t         <input id=\"emailfield\" type=\"text\" name=\"email\" class=\"input\" value=\"E-mail\" onChange=\"checkemail( this.value)\" onfocus=\"this.value=''\"><br><label class=\"alert\" style=\"visibility: hidden\" id=\"email_alert\"> Email field cannot be empty</label>\r\n");
      out.write("\t\t         <input id=\"userfield\" type=\"text\" value=\"Username\" class=\"input\" name=\"username\" onfocus=\"this.value=''\"><label class=\"alert\" style=\"visibility: hidden\" id=\"username2_alert\" onfocus=\"this.value=''\"> Username field cannot be empty</label>\r\n");
      out.write("\t\t         <br><br><span>Please type your password below</span>\r\n");
      out.write("\t\t         <input id=\"pass1field\" type=\"password\" class=\"input\" name=\"pass1\" onfocus=\"this.value=''\"><label class=\"alert\" style=\"visibility: hidden\" id=\"pass1_alert\"> Password field cannot be empty</label>\r\n");
      out.write("\t\t         <br><span>Please retype your password below</span>\r\n");
      out.write("\t\t         <input id=\"pass2field\" type=\"password\" class=\"input\" name=\"pass2\" onfocus=\"this.value=''\"><label class=\"alert\" style=\"visibility: hidden\" id=\"pass2_alert\"> Password field cannot be empty</label>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    <div class=\"footer\">\r\n");
      out.write("\t\t         <input id=\"register_submit\" type=\"submit\" class=\"button\" name=\"submit\" onclick=\"return isEmpty( this.id);\" value=\"Sign Up\">\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("        </form>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
